//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace expert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("expert.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Ambition {
            get {
                return ResourceManager.GetString("Ambition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue is best for banking.
        /// </summary>
        internal static string Banking {
            get {
                return ResourceManager.GetString("Banking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange and Green.
        /// </summary>
        internal static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        internal static string Calmness {
            get {
                return ResourceManager.GetString("Calmness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does your slogan represent more?.
        /// </summary>
        internal static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Colors! What does your slogan represent more?.
        /// </summary>
        internal static string Dessert {
            get {
                return ResourceManager.GetString("Dessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string EnergeticSour {
            get {
                return ResourceManager.GetString("EnergeticSour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which suits your slogan more?.
        /// </summary>
        internal static string FastFood {
            get {
                return ResourceManager.GetString("FastFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Growth {
            get {
                return ResourceManager.GetString("Growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a hospital?.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grren, White, or Beige.
        /// </summary>
        internal static string HealthyFood {
            get {
                return ResourceManager.GetString("HealthyFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a pharmacy or a clinic?.
        /// </summary>
        internal static string HospitalNo {
            get {
                return ResourceManager.GetString("HospitalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string HospitalYes {
            get {
                return ResourceManager.GetString("HospitalYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Colors! What represents your slogan more?.
        /// </summary>
        internal static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string LessHeat {
            get {
                return ResourceManager.GetString("LessHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you care more about safety, success, or both?.
        /// </summary>
        internal static string OnlineBanking {
            get {
                return ResourceManager.GetString("OnlineBanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your slogan represent positivity?.
        /// </summary>
        internal static string Pharmacy {
            get {
                return ResourceManager.GetString("Pharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Positivity {
            get {
                return ResourceManager.GetString("Positivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green suits it anyway!.
        /// </summary>
        internal static string PositivityNo {
            get {
                return ResourceManager.GetString("PositivityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string PositivityYes {
            get {
                return ResourceManager.GetString("PositivityYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Royalty {
            get {
                return ResourceManager.GetString("Royalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Safety {
            get {
                return ResourceManager.GetString("Safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Spicy {
            get {
                return ResourceManager.GetString("Spicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your brand&apos;s industry?.
        /// </summary>
        internal static string StartQuestion {
            get {
                return ResourceManager.GetString("StartQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        internal static string Trust {
            get {
                return ResourceManager.GetString("Trust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string VerySweet {
            get {
                return ResourceManager.GetString("VerySweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Brand Theme Guru.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
